add codeceptjs with tests
patrjam/react-web-example pull request #1
Opened 2020-04-21 16:49 UTC by patrjam

2020-04-22 10:07 UTC, Trawais commented on package.json
> +    "test:lvl-1": "codeceptjs run --config=./automation-example/configs/level-1.config.conf.js --debug",
Do we have some better name for these "levels"?

2020-04-22 10:07 UTC, Trawais commented on .gitignore
> +.env
missing an empty line at the end of the file

2020-04-24 09:30 UTC, CDJojn requested changes

2020-04-24 09:30 UTC, CDJojn commented on automation-example/configs/level-1.config.conf.js
> +    I: '../../steps_file.js'
why are you not use jsqa/step_file.js ??

2020-04-24 09:30 UTC, CDJojn commented on automation-example/configs/level-1.config.conf.js
> +  plugins: {
no wdio plugin?

2020-04-24 09:30 UTC, CDJojn commented on automation-example/pages/App/App.js
> +  application: '[id="root"]',
why is here this file?

2020-04-24 09:30 UTC, CDJojn commented on automation-example/pages/Messages/Success.js
> +module.exports = {
I'm not sure if this is good approach... this is not PAGE, just text message and why is this file not part of autoload or part of page where is located.... missing context.

2020-04-24 09:30 UTC, CDJojn commented on automation-example/pages/Header/Header.js
> +module.exports = {
same situation this should be components or what?

2020-04-24 09:30 UTC, CDJojn commented on automation-example/tests/level-3/fill-form-3_test.js
> +  //NOTE: need to add data-qa in to code
clear note?

2020-04-24 09:30 UTC, CDJojn commented on steps_file.js
> +module.exports = function() {
remove and use from JSQA

2020-04-28 11:49 UTC, CDJojn commented on automation-example/pages/Form/FormPage.js
> +  async fillInNameWithScudUser() {
split into 2 methods - fillwithName() and getScudUser() - what is direct method if DataClientHelper - this call should be part of test, not part od PageObject

2020-05-05 11:43 UTC, merged